#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=10
STOP=98

system_config() {
	local cfg="$1"

	local hostname conloglevel timezone

	config_get hostname "$cfg" hostname 'OpenWrt'
	echo "$hostname" > /proc/sys/kernel/hostname

	config_get conloglevel "$cfg" conloglevel
	config_get buffersize "$cfg" buffersize
	[ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}
	
	config_get timezone "$cfg" timezone 'UTC'
	echo "$timezone" > /tmp/TZ

        # Set init date to April 1st 2013
        date -u -s 2013.04.01-00:00:00

	if [ -x /sbin/syslogd ]; then
		local log_ip log_size log_port log_type log_file
		config_get log_ip "$cfg" log_ip 
		config_get log_size "$cfg" log_size 256
		config_get log_port "$cfg" log_port 514
		config_get log_type "$cfg" log_type circular
		config_get log_file "$cfg" log_file "/var/log/messages"
		if [ "$log_type" = "file" ]; then
			syslogd -s $log_size -O $log_file ${log_ip:+-L -R ${log_ip}:${log_port}} -S
		else
			syslogd -C${log_size} ${log_ip:+-L -R ${log_ip}:${log_port}}
		fi
	fi
	config_get klogconloglevel "$cfg" klogconloglevel
	[ -x /sbin/klogd ] && klogd ${klogconloglevel:+-c $klogconloglevel}
}

apply_uci_config() {
	sh -c '. /etc/functions.sh; include /lib/config; uci_apply_defaults'
}

start() {
	[ -f /proc/mounts ] || /sbin/mount_root
	[ -f /proc/jffs2_bbc ] && echo "S" > /proc/jffs2_bbc
	[ -f /proc/net/vlan/config ] && vconfig set_name_type DEV_PLUS_VID_NO_PAD

	apply_uci_config
	config_load system
	config_foreach system_config system
	
	mkdir -p /var/run
	mkdir -p /var/log
	mkdir -p /var/lock
	mkdir -p /var/state
	mkdir -p /tmp/.uci
	chmod 0700 /tmp/.uci
        mkdir -p /tmp/mnt
	touch /var/log/wtmp
	touch /var/log/lastlog
	grep -q debugfs /proc/filesystems && mount -t debugfs debugfs /sys/kernel/debug
	[ "$FAILSAFE" = "true" ] && touch /tmp/.failsafe

	# create /dev/root if it doesn't exist
	[ -e /dev/root ] || {
		rootdev=$(awk 'BEGIN { RS=" "; FS="="; } $1 == "root" { print $2 }' < /proc/cmdline)
		[ -n "$rootdev" ] && ln -s "$rootdev" /dev/root
	}

	load_modules /etc/modules.d/*
}

stop() {
        killall -9 syslogd 2> /dev/null
}

