#!/bin/sh /etc/rc.common

START=50


start() {
	if [ -d /www/gui/provider ]
	then
		rm -rf /usr/lib/asterisk/provider
		ln -s /www/gui/provider /usr/lib/asterisk/provider
	fi
	mkdir -p /tmp/asterisk
	touch /tmp/asterisk/profile.inc
}

stop() {
	echo "DOWN"
}
