#!/bin/sh

. /usr/bin/pcb_common.sh

name="deviceinfo_plugin"
start_options="-c /usr/lib/deviceinfo/deviceinfo.odl"
datamodel="DeviceInfo"
trace_zones="deviceinfo"
component="sah_services_system"

case $1 in
    start)
        pcb_start $name $start_options
        ;;
    stop)
        pcb_stop $name
        ;;
    restart)
        pcb_restart $name $start_options
        ;;
    debuginfo)
        pcb_debug_info $name $component $datamodel
        ;;
    log)
       action=$2
       if [ -n "$action" ]; then
           pcb_log $name $action $trace_zones
       else
           pcb_log $name enable $trace_zones
       fi
       ;;
    backup)
        if pcb_is_running $name ; then
            pcb_cli -q "DeviceInfo.export($2)"
        else
            echo "DeviceInfo is not running, impossible to make a backup"
        fi
        ;;
    restore)
        mkdir -p /var/lib/deviceinfo
        touch /var/lib/deviceinfo/restore
        ;;
    *)
        echo "Usage : $0 [start|stop|restart|debuginfo|log|backup|restore]"
        ;;
esac
