#!/bin/sh

. /usr/bin/pcb_common.sh

name="passwordrecovery"
odl="/usr/lib/$name/$name.odl"
start_options="-c $odl"
datamodel="PasswordRecovery"
trace_zones=""
component="sah_services_passwordrecovery"

start() {
    if [ -e /etc/environment ]; then
        . /etc/environment
    fi

    if pcb_is_running $name; then   
        echo "usermngt service already started"
        exit 1;
    fi

    export WLAN_KEY
    pcb_start $name $start_options
}

case $1 in
    start)
        start
        ;;
    stop)
        pcb_stop $name
        ;;
    debuginfo)
        pcb_debug_info $name $component $datamodel
        ;;
    log)
        action=$2
        if [ -n "$action" ]; then
            pcb_log $name $action $trace_zones
        else
            pcb_log $name enable $trace_zones
        fi
        ;;
    *)
        echo "Usage : $0 [start|stop|debuginfo|log]"
        ;;
esac

