#!/bin/sh

. /usr/bin/pcb_common.sh

name="message_plugin"
start_options="-c /usr/lib/message/message_plugin.odl"
datamodel="Message"
trace_zones=""
component="sah_services_message"

case $1 in
    start)
        pcb_start $name $start_options
        ;;
    stop)
        pcb_stop $name
        ;;
    restart)
        pcb_restart $name $start_options
        ;;
    debuginfo)
        pcb_debug_info $name $component $datamodel
        ;;
    log)
       action=$2
       if [ -n "$action" ]; then
           pcb_log $name $action $trace_zones
       else
           pcb_log $name enable $trace_zones
       fi
       ;;
    *)
        echo "Usage : $0 [start|stop|restart|debuginfo|log]"
        ;;
esac
