#!/bin/sh

case $1 in
    start)
        pcb_cli -q "NeMo.Intf.lan.setParameters(\"Enable\", \"true\", \"eth || switch\", \"down\")"
        ;;
    stop)
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 [start|stop|restart]"
        ;;
esac
