#!/bin/sh
PID="/var/run/smbmanager.pid"
NAME=smbmanager
ODL=/usr/lib/smbmanager/smbmanager.odl

start() {
    if [ -e "${PID}" ]; then
        echo "smbmanager service already started"
        exit 1;
    fi
    pcb_plugin -n $NAME -c "${ODL}"
    pidof $NAME > $PID
}

stop() {
    if [ -e "${PID}" ]; then
        kill $(cat $PID)
    else
        echo "smbmanager not running"
        exit 1
    fi
}

case $1 in
    backup)
        ;;
    restore)
        ;;
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 [start|stop|restart|backup|restore]"
        ;;
esac
