#!/bin/sh

CONFIG_FILE="/proc/net/netfilter/nf_dyndscp_w2ldscp_transtbl"

case $1 in
    start)
        WAN_INTF="`pcb_cli -l \"NeMo.Intf.lo.luckyIntf(\"wan\", all)\"`"
        [ "$WAN_INTF" != "" ] && echo "setwanif $WAN_INTF" > "$CONFIG_FILE"

        echo "add 0x38 0x20" > "$CONFIG_FILE"
        echo "add 0x30 0x20" > "$CONFIG_FILE"
        echo "add 0x2e 0x30" > "$CONFIG_FILE"
        echo "add 0x28 0x30" > "$CONFIG_FILE"
        echo "add 0x26 0x20" > "$CONFIG_FILE"
        echo "add 0x24 0x20" > "$CONFIG_FILE"
        echo "add 0x22 0x20" > "$CONFIG_FILE"
        echo "add 0x20 0x20" > "$CONFIG_FILE"
        echo "add 0x1e 0x20" > "$CONFIG_FILE"
        echo "add 0x1c 0x20" > "$CONFIG_FILE"
        echo "add 0x1a 0x20" > "$CONFIG_FILE"
        echo "add 0x18 0x20" > "$CONFIG_FILE"
        echo "add 0x12 0x28" > "$CONFIG_FILE"
        ;;
    *)
        echo "Usage: $0 [start]"
        ;;
esac
