#!/bin/sh


. /usr/bin/pcb_common.sh

name="www-backend"
start_options="-c /usr/lib/www-backend/www-backend.odl"
datamodel="UserInterface"
trace_zones=""
component="sah_services_www_backend"

case $1 in
    start)
        pcb_start $name $start_options
        ;;
    stop)
        pcb_stop $name
        ;;
    restart)
        $0 stop
        $0 start
        ;;
    backup)
        if pcb_is_running $name ; then
            pcb_cli "UserInterface.export($2)"
        else
            echo "UserInterface plugin is not running, impossible to make a backup"
        fi
        ;;
    restore)
        mkdir -p /var/lib/www-backend
        touch /var/lib/www-backend/restore

        if [ ! -e "/etc/config/hgwcfg.usr" ]; then
            touch /var/lib/www-backend/reset-hard
        fi
        ;;
    debuginfo)
        pcb_debug_info $name $component $datamodel
        ;;
    log)
        action=$2
        if [ -n "$action" ]; then
            pcb_log $name $action $trace_zones
        else
            pcb_log $name enable $trace_zones
        fi
        ;;
    *)
        echo "Usage : $0 [start|stop|restart|debuginfo|log]"
        ;;
esac
