#!/bin/sh
echo Number of arguments passed: $#

sysutil athr83xxconf --vlan --ingress --ports 0 1 2 3 4 --mode secure
sysutil athr83xxconf --vlan --port 0 --ports 1 2 3 4 5 6 --pvid 1
sysutil athr83xxconf --vlan --port 1 --ports 0 2 3 4 5 6 --pvid 1
sysutil athr83xxconf --vlan --port 2 --ports 0 1 3 4 5 6 --pvid 1
sysutil athr83xxconf --vlan --port 3 --ports 0 1 2 4 5 6 --pvid 2
sysutil athr83xxconf --vlan --port 4 --ports 0 1 2 3 5 6 --pvid 3
echo  dummy 
sysutil athr83xxconf --writereg 0x0610 0x001bfd60
sysutil athr83xxconf --writereg 0x0614 0x80010002
sysutil athr83xxconf --readreg 0x0614
sysutil athr83xxconf --readreg 0x0610 
echo Insert VLAN 1 
#sysutil athr83xxconf --writereg 0x0610 0x001bfd60
#sysutil athr83xxconf --writereg 0x0614 0x80010002
sysutil athr83xxconf --vlan --addtag --ports 0 1 2 --vid 1
#sysutil athr83xxconf --readreg 0x0614
#sysutil athr83xxconf --readreg 0x0610  
echo Insert VLAN 2 
#sysutil athr83xxconf --writereg 0x0610 0x001bf7e0
#sysutil athr83xxconf --writereg 0x0614 0x80020002
sysutil athr83xxconf --vlan --addtag --ports 0 3 --vid 2
#sysutil athr83xxconf --readreg 0x0614
#sysutil athr83xxconf --readreg 0x0610
echo Insert VLAN 3 
#sysutil athr83xxconf --writereg 0x0610 0x001bdfe0
#sysutil athr83xxconf --writereg 0x0614 0x80030002
sysutil athr83xxconf --vlan --addtag --ports 0 4 --vid 3
#sysutil athr83xxconf --readreg 0x0614
#sysutil athr83xxconf --readreg 0x0610

sysutil athr83xxconf --vlan --egress --ports 0 --mode tagged
sysutil athr83xxconf --vlan --egress --ports 1 2 3 4 --mode untagged
echo dump registers 
sysutil athr83xxconf --readreg 0x0660
sysutil athr83xxconf --readreg 0x066c
sysutil athr83xxconf --readreg 0x0678
sysutil athr83xxconf --readreg 0x0684
sysutil athr83xxconf --readreg 0x0690
sysutil athr83xxconf --readreg 0x0420
sysutil athr83xxconf --readreg 0x0428
sysutil athr83xxconf --readreg 0x0430
sysutil athr83xxconf --readreg 0x0438
sysutil athr83xxconf --readreg 0x0440
sysutil athr83xxconf --readreg 0x0424
sysutil athr83xxconf --readreg 0x042c
sysutil athr83xxconf --readreg 0x0434
sysutil athr83xxconf --readreg 0x043c
sysutil athr83xxconf --readreg 0x0444
sysutil athr83xxconf --writereg 0x210 0x0
sysutil athr83xxconf --writereg 0x214 0x0





