#!/bin/sh
TARGET_DIR="/var/lib/wld"

case $1 in
	start)
		logger -t wifi "Firewall changes for wps upnp"
		pcb_cli -q "Firewall.setService(wps_upnp, lan, \"49152,49153\",6,4,true)"
		logger -t wifi "Create wld target directory"
		mkdir -p -m 700 "$TARGET_DIR"
		chmod 700 "$TARGET_DIR"
		sahenv -f /etc/environment LD_LIBRARY_PATH=/usr/lib/wld:/usr/lib/wld/ath WIFIROOT=WiFiATH \
			pcb_plugin -n wld_ath -I /var/run/wld_ath -c /usr/lib/wld/wld.odl
		pcb_cli -q "NeMo.Module.wlan.addVendor(root=\"WiFiATH\", suffix=\"_ath\", dst=\"pcb://ipc:[/var/run/wld_ath]\")"
		;;
	stop)
		pcb_cli "NeMo.Module.wlan.deleteVendor(root=\"WiFiATH\")"
		[ -e /var/run/wld_ath.pid ] && kill `cat /var/run/wld_ath.pid`
		;;
	*)
		echo "Usage: $0 [start|stop]"
esac

