#!/bin/sh




BMEFILE=/etc/config/ADSL
BINFILE=/bin/Code_VX185.BIN

case $1 in
	start)
		# create any hardware-specific device nodes here
		mknod /dev/dsp c 115 15
		mknod /dev/voice c 115 16
		mknod /dev/fxo c 115 17
		mknod /dev/t38dev c 115 18
		mknod /dev/dect	c 115 19

		# start hardware-specific drivers
		# modprobe ...
		/sbin/modprobe fb
		/sbin/modprobe pwrmgmtdrv_lkm
		/sbin/modprobe fusivlib_lkm
		/sbin/modprobe timers_lkm
		/sbin/modprobe ap2ap_lkm
		/sbin/modprobe bmdriver_lkm
		/sbin/modprobe ethdriver_lkm eth0_mii=2 eth1_mii=1
		/sbin/modprobe sysKCode_lkm
		/sbin/modprobe periap_driver_lkm
		/sbin/modprobe aclap_driver_lkm
		/sbin/modprobe bmedrv
		/sbin/modprobe ipqos_lkm
		/sbin/modprobe monif_lkm
		/sbin/modprobe spi_driver_lkm
		/sbin/modprobe oleddrv autoOffDelay=0 deferredIoDelay=20
		/sbin/modprobe dspvoice
		/sbin/modprobe athr83xx_lkm
		/sbin/modprobe igmpsnoop_lkm
		/sbin/modprobe ehci-hcd

		if [ -e /var/run/VDSL ]; then
			/sbin/modprobe vdsldriver_lkm
			logger -p INFO -t hardware "Load VDSL driver"
		else
			/sbin/modprobe atmdriver_lkm
			logger -p INFO -t hardware "Load ATM driver"
		fi

		mknod /dev/led c `sed -n 's/\(.*\) led$/\1/p' /proc/devices` 0
		button_major=`sed -n 's/\(.*\) lb_button$/\1/p' /proc/devices`
		for f in 0 1 2 3 4; do
			mknod /dev/button$f c $button_major $f 2>/dev/null
		done

		ln -s /dev/button0 /dev/button_wlan_pairing
		ln -s /dev/button0 /dev/button_dect
		ln -s /dev/button0 /dev/button_nbr_cancel_2
		ln -s /dev/button1 /dev/button_reboot
		ln -s /dev/button2 /dev/button_reset
		ln -s /dev/button2 /dev/button_screen_reset_push
		ln -s /dev/button2 /dev/button_screen_reset_release
		ln -s /dev/button3 /dev/button_wlan
		ln -s /dev/button3 /dev/button_screen_wlan
		ln -s /dev/button3 /dev/button_nbr_cancel_1
		ln -s /dev/button4 /dev/button_screen

		mkdir -p /var/dev/led

		[ -d /sys/class/leds/led_0 ] && ln -s /sys/class/leds/led_0 /var/dev/led/Power
		[ -d /sys/class/leds/led_1 ] && ln -s /sys/class/leds/led_1 /var/dev/led/InternetRed
		[ -d /sys/class/leds/led_2 ] && ln -s /sys/class/leds/led_2 /var/dev/led/Internet
		[ -d /sys/class/leds/led_3 ] && ln -s /sys/class/leds/led_3 /var/dev/led/Voip
		[ -d /sys/class/leds/led_4 ] && ln -s /sys/class/leds/led_4 /var/dev/led/Lan
		[ -d /sys/class/leds/led_5 ] && ln -s /sys/class/leds/led_5 /var/dev/led/Wireless
		[ -d /sys/class/leds/led_6 ] && ln -s /sys/class/leds/led_6 /var/dev/led/Upgrade

		mkdir -p /var/dev/led/StatusRed
		mkdir -p /var/dev/led/StatusGreen

		ln -s /proc/led-screen-red   /var/dev/led/StatusRed/brightness
		ln -s /proc/led-screen-green /var/dev/led/StatusGreen/brightness

		mkdir -p /var/dev/led/Backlight
		ln -s /proc/oled_contrast /var/dev/led/Backlight/brightness

		mkdir -p /var/dev/led/InternetRed

		# copy the DSL fw on the RW fs
		if [ ! -e $BINFILE ]
		then
			cp /bin/Code_VX185.BIN $BINFILE
		fi

		# force min_free_kbytes
		[ -f /proc/sys/vm/min_free_kbytes ] && /bin/echo 2792 > /proc/sys/vm/min_free_kbytes
	;;
	stop)
		# stop drivers if necessary
		echo "stop CSSP specific drivers"
	;;
	*)
	;;
esac

