#!/bin/sh

. /usr/bin/pcb_common.sh

name="webuiupgrade_plugin"
datamodel="WebuiupgradeService"
trace_zones=""
component="sah_services_webuiupgrade"

RESTORE="/var/lib/webuiupgrade_plugin/restore"

case $1 in
    start)
        pcb_start $name
        ;;
    stop)
        pcb_stop $name
        ;;
    backup)
        if pcb_is_running $name ; then
            pcb_cli "WebuiupgradeService.export($2)"
        else 
            echo "webuiupgrade plugin is not running, impossible to make a backup"
        fi                 
        ;;
    restore)
        mkdir -p $(dirname "${RESTORE}") && touch "${RESTORE}"
        ;;
    debuginfo)
        pcb_debug_info $name $component $datamodel
        ;;
    log)
        action=$2
        if [ -n "$action" ]; then
            pcb_log $name $action $trace_zones
        else
            pcb_log $name enable $trace_zones
        fi
        ;;
    *)
        echo "Usage : $0 [start|stop|backup|restore|debuginfo|log]"
        ;;
esac

