#!/bin/sh

case $1 in
	start)
		modprobe lanled
		mknod /dev/lanled c `sed -nr "s| *([0-9]*) lanled|\1|p" /proc/devices` 0
		mafia pcb_client -vvv -n lanled -s /usr/lib/lanled/lanled.so
		;;
	stop)
		killall lanled
		modprobe -r lanled
		;;
	*)
		echo "Usage: $0 [start|stop]"
		;;
esac
