#!/bin/sh



case $1 in
	start)

		if [ ! -e /etc/dropbear/dropbear_rsa_host_key ]
		then
			mkdir -p /etc/dropbear 1>/dev/null 2>/dev/null
			/bin/dropbearkey -t rsa -f /etc/dropbear/dropbear_rsa_host_key > /dev/null 2>&1
		fi
		touch /var/log/lastlog /var/log/wtmp
	;;
	stop)
		;;
	*)
esac
