#!/bin/sh
# Copyright (C) 2006 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

init_device_fs() {
    echo > /dev/mdev.seq
    sysctl -w kernel.hotplug=/sbin/mdev
    /sbin/mdev -s
}

boot_hook_add preinit_essential init_device_fs

