[common]
include => keypad_CF
include => keypad_queue
include => local_static
include => directory
include => keypad_install
include => keypad_callwaiting
include => keypad_privacy
include => keypad_RingBack
include => keypad_CF_queue
include => keypad_Password_change
include => keypad_CLIP
include => keypad_PhoneLock
include => BLF_pickup
include => keypad_CCBS
include => keypad_CCBS_Current
include => keypad_CallPickUpProtection
include => Keypad_annuaire
