RGSRC=../../../
include $(RGSRC)/envir.mak

RAMDISK_IMG_FILES+= arrowrightorange.png \
					bottom.gif \
					bottomright.gif \
					expand.png \
					leftsep.gif \
					leftsepbig.gif \
					right.gif \
					sep.gif \
					sepbig.gif \
					topleft.gif \
					arrowrightwhite.png \
					bottomleft.gif \
					collapse.png \
					left.gif \
					Makefile \
					rightsep.gif \
					top.gif \
					topright.gif


RAMDISK_FILES=$(RAMDISK_IMG_FILES:%=/home/httpd/html/images/menu/%)

include $(RGMK)


