#!/bin/sh /etc/rc.common
# Copyright (C) 2008  Alina Friedrichsen <x-alina@gmx.net>
START=50

start() {
	echo Create devices /dev/dectUSB for Sagemcom DECT USB driver
	mknod /dev/dectUSB      c   240 0
	mknod /dev/dectUSB_cmd  c   240 1
}

stop() {
	echo stop devices
}
