#!/bin/sh /etc/rc.common
# Copyright (C) 2008  Alina Friedrichsen <x-alina@gmx.net>
START=50

start() {
	echo Create devices /dev/rtp for Sagemcom RTP driver
	mknod /dev/rtp       c   231 15
	mknod /dev/rtpT38    c   231 16
}

stop() {
	echo stop devices
}
