#!/bin/sh /etc/rc.common
# Copyright (C) 2008  Alina Friedrichsen <x-alina@gmx.net>
START=50

start() {
   echo Disable CRC in BCSP packets > /dev/console
   echo 0 > /sys/module/hci_uart/parameters/txcrc

	echo Register thomson usb dect dongle in cp2101 driver > /dev/console
	echo 06b9 6000 > /sys/bus/usb-serial/drivers/cp2101/new_id
	
	echo Register Orange generic usb dect dongle in cp2101 driver > /dev/console
        echo 0bdd 0100 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0101 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0110 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0111 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0120 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0121 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0130 > /sys/bus/usb-serial/drivers/cp2101/new_id
        echo 0bdd 0131 > /sys/bus/usb-serial/drivers/cp2101/new_id
}

stop() {
	echo stop devices
}
