#!/bin/sh
PIDEMANAGER="/var/run/eventmanager.pid"
EMANAGER="pcb_plugin -vv -n eventmanager -c /usr/lib/eventmanager/eventmanager.odl"

start() {
    echo "Starting pcb eventmanager"
    ${EMANAGER}
}

stop() {
    if [ -e ${PIDEMANAGER} ]; then
        echo "Stopping pcb eventmanager"
        kill $(cat ${PIDEMANAGER});
    else
        echo "pcb eventmanager already stopped"
    fi
}

restart() {
    stop
    while test -e ${PIDEMANAGER}; do
        sleep 1
    done
    start
}

case $1 in
    start)
        start
	;;
    stop)
        stop
	;;
    restart)
        restart
        ;;
    *)
        ;;
esac
