#!/bin/sh
PIDIGDMAPPER="/var/run/igd_mapper.pid"
IGDMAPPER="/bin/pcb_plugin -I /var/run/IGD -vv -n igd_mapper -N IGD -c /usr/lib/igd_mapping/igd.odl"

start() {
    if [ -e ${PIDIGDMAPPER} ]; then
        echo "pcb igd mapper already started"
    else
        echo "Starting pcb igd mapper"
        export CONFIG_PREFIX_NON_STANDARD=X_ORANGE-COM_
        PCB_MAIN_BUS="ipc:{/var/run/pcb_sys}" MBUS_ATOMIC="ipc:{/var/run/pcb_sys}" ${IGDMAPPER};
    fi
}

stop() {
    if [ -e ${PIDIGDMAPPER} ]; then
        echo "Stopping pcb igd mapper"
        kill $(cat ${PIDIGDMAPPER});
    else
        echo "pcb igd mapper already stopped"
    fi

}

restart() {
    stop
    while test -e ${PIDIGDMAPPER}; do
        sleep 1
    done
    start
}

case $1 in
    start)
        start
	;;
    stop)
        stop
	;;
    restart)
        restart
        ;;
    *)
        ;;
esac

