#!/bin/sh
#
# This script is run by the pppd after the link is established.
# It uses run-parts to run scripts in /etc/ppp/ip-up.d, so to add routes,
# set IP address, run the mailq etc. you should create script(s) there.
#
# Be aware that other packages may include /etc/ppp/ip-up.d scripts (named
# after that package), so choose local script names with that in mind.
#
# This script is called with the following arguments:
#    Arg  Name                          Example
#    $1   Interface name                ppp0
#    $2   The tty                       ttyS1
#    $3   The link speed                38400
#    $4   Local IP number               12.34.56.78
#    $5   Peer  IP number               12.34.56.99
#    $6   Optional ``ipparam'' value    foo
# The following environment variables are set :
#    Name              Example
#    $PPPOE_SESSION    4444
#    $MACREMOTE        AA:BB:CC:DD:EE:FF
#    $AUTH_WITHPEER_PROT CHAP

# The  environment is cleared before executing this script
# so the path must be reset
PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin
export PATH

# These variables are for the use of the scripts run by run-parts
PPP_IFACE="$1"
PPP_TTY="$2"
PPP_SPEED="$3"
PPP_LOCAL="$4"
PPP_REMOTE="$5"
PPP_IPPARAM="$6"

if [ "x$PPPOE_SESSION" == "x" ]; then
	PPPOE_SESSION=0
fi
if [ "x$MACREMOTE" == "x" ]; then
	MACREMOTE=0
fi
if [ "x$AUTH_WITHPEER_PROT" == "x" ]; then
	AUTH_WITHPEER_PROT=0
fi

pppd2smuPppAdaptor $PPP_IPPARAM ip-up $PPP_IFACE $PPPOE_SESSION $MACREMOTE $PPP_LOCAL $PPP_REMOTE $AUTH_WITHPEER_PROT $DNS1 $DNS2 
